BEGIN TRANSACTION;
CREATE TABLE `Tag` (
	`Tag_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Tag_Keyword`	TEXT NOT NULL
);
CREATE TABLE `Datatype` (
	`Datatype_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Datatype_Name`	INTEGER NOT NULL
);
CREATE TABLE `Algo_Tag` (
	`Algo_ID`	INTEGER NOT NULL,
	`Tag_ID`	INTEGER NOT NULL,
	PRIMARY KEY(Algo_ID,Tag_ID),
	FOREIGN KEY(`Algo_ID`) REFERENCES Algo(Algo_ID),
	FOREIGN KEY(`Tag_ID`) REFERENCES Tag(Tag_ID)
);
CREATE TABLE "Algo_Datatype" (
	`Algo_ID`	INTEGER NOT NULL,
	`Datatype_ID`	INTEGER NOT NULL,
	PRIMARY KEY(Algo_ID,Datatype_ID),
	FOREIGN KEY(`Algo_ID`) REFERENCES Algo ( Algo_ID ),
	FOREIGN KEY(`Datatype_ID`) REFERENCES Datatype ( Datatype_ID )
);
CREATE TABLE `Algo` (
	`Algo_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Algo_Name`	TEXT NOT NULL,
	`Algo_Manifest`	TEXT NOT NULL
);
COMMIT;
